name: Tests
on:
  workflow_call:
jobs:
  missing-includes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for missing includes in LibCustomIcons.addon
        run: |
          python3 .github/scripts/check-includes.py
  duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for duplicate definitions
        run: |
          python3 .github/scripts/check-duplicates.py
